#include "common/mil-std-3071_data_model.idl"

module cli {

  const string TOPIC_POWER_DEVICES_REQUEST = "Power Devices Request";
  const string TOPIC_POWER_DEVICES_REPLY = "Power Devices Reply";
  const string TOPIC_CONTROLLER_COMMAND = "Controller Command";

  @topic
  @extensibility(FINAL)
  struct PowerDevicesRequest {
    @key tms::Identity mc_id;
  };

  @nested
  @extensibility(FINAL)
  struct PowerDeviceInfo {
    tms::DeviceInfo device_info;
    tms::EnergyStartStopLevel essl;
    // The MC that controls this device.
    // Obtain from tms::ActiveMicrogridControllerState sent by the device.
    @optional tms::Identity master_id;
  };

  typedef sequence<PowerDeviceInfo> PowerDeviceInfoSeq;

  @topic
  @extensibility(FINAL)
  struct PowerDevicesReply {
    @key tms::Identity mc_id;
    PowerDeviceInfoSeq devices;
  };

  enum ControllerCmdType {
    CCT_STOP,
    CCT_RESUME,
    CCT_TERMINATE
  };

  @topic
  @extensibility(FINAL)
  struct ControllerCommand {
    @key tms::Identity mc_id;
    ControllerCmdType type;
  };

};
